[package]
name = "rust-gb"
version = "0.1.0"
authors = ["plozano <pabloloz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8" }
num-traits = "0.2"
bitflags = "1.0"

[dependencies.failure]
version = "~0.1"

[dependencies.failure_derive]
version = "~0.1"

[dev-dependencies]
quickcheck = "0.9"