[package]
name = "gb-core"
version = "0.1.0"
authors = ["plozano <plozano@24hourfit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"
num = { version = "0.3.1", default-features = false }
num-derive = "0.3.3"
num-traits = { version = "0.2.14", default-features = false }
arrayvec = { version = "0.5.2", default-features = false }
unroll= "0.1.5"

[dependencies.failure_derive]
version = "~0.1"

[dependencies.enum-display-derive]
version = "0.1.0"

[dev-dependencies]
quickcheck = "0.9"

[profile.release]
debug = 1